### ISSUE TITLE
bug report: Type error

### ISSUE THREAD

**Issue by ThisIsIsaac** [openai/random-network-distillation#20]
Type error when running: `python run_atari.py --gamma_ext 0.999`

and have applied below changes in `mpi_util.py`:

`available_gpus = guess_available_gpus()`-> `available_gpus = 1`
and
`os.environ['CUDA_VISIBLE_DEVICES'] = str(1)` -> `os.environ['CUDA_VISIBLE_DEVICES'] = str(available_gpus[local_rank])`

```
Traceback (most recent call last):
  File "run_atari.py", line 150, in <module>
    main()
  File "run_atari.py", line 146, in main
    num_timesteps=args.num_timesteps, hps=hps)
  File "run_atari.py", line 65, in train
    ext_coeff=hps.pop('ext_coeff'),
  File "/home/isaac/random-network-distillation/ppo_agent.py", line 137, in __init__
    self.stochpol = stochpol_fn()
  File "/home/isaac/random-network-distillation/policies/cnn_gru_policy_dynamics.py", line 80, in __init__
    rec_gate_init=rec_gate_init
  File "/home/isaac/random-network-distillation/policies/cnn_gru_policy_dynamics.py", line 134, in apply_policy
    dtype=tf.float32, time_major=False, initial_state=ph_istate)
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 707, in dynamic_rnn
    dtype=dtype)
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 916, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3501, in while_loop
    return_same_structure)
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3012, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2937, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3456, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 884, in _time_step
    (output, new_state) = call_cell()
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 870, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 248, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 149, in wrapper
    raise e.ag_error_metadata.to_exception(type(e))
TypeError: in converted code:

    /home/isaac/random-network-distillation/policies/cnn_gru_policy_dynamics.py:35 call *
        mr = tf.sigmoid(fc(hx, nh=self._num_units * 2, scope='mr', init_bias=self.rec_gate_init))
    /home/isaac/random-network-distillation/utils.py:10 fc *
        w = tf.get_variable("w", [nin, nh], initializer=ortho_init(init_scale))
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py:1496 get_variable
        aggregation=aggregation)
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py:1239 get_variable
        aggregation=aggregation)
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py:545 get_variable
        return custom_getter(**custom_getter_kwargs)
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py:251 _rnn_get_variable
        variable = getter(*args, **kwargs)
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py:514 _true_getter
        aggregation=aggregation)
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py:929 _get_single_variable
        aggregation=aggregation)
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/variables.py:259 __call__
        return cls._variable_v1_call(*args, **kwargs)
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/variables.py:220 _variable_v1_call
        shape=shape)
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/variables.py:198 <lambda>
        previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py:2511 default_variable_creator
        shape=shape)
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/variables.py:263 __call__
        return super(VariableMetaclass, cls).__call__(*args, **kwargs)
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/variables.py:1568 __init__
        shape=shape)
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/variables.py:1698 _init_from_args
        initial_value(), name="initial_value", dtype=dtype)
    /home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py:901 <lambda>
        partition_info=partition_info)
    /tmp/tmpj_ytdoym.py:51 _ortho_init
        retval__1 = ag__.converted_call('astype', scale * q[:shape[0], :shape[1]], ag__.ConversionOptions(recursive=True, force_conversion=False, optional_features=(), internal_convert_user_code=True), (np.float32,), None)

    TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

**Comment by maitchison** [comment]
This might be a TensorFlow version thing. I'm on V1.14 an also having this problem. I tried switching the policy from RNN to CNN and it seems work, but I still can't get the RNN one going.
